config/routes.rb
Evescore::Application.routes.draw do
  resources :sigs

  get "trust/grant"
  resources :scans do
    resources :sigs
  end
  
  get "scan/:secure_id", to: "scans#show"
  get "scan/:secure_id/edit", to: "scans#edit"
  get "tools/dps"
  get "stats/factions"
  get "stats/progress"
  resources :corps

  get "top/rats"
  get "top/ticks"
  get "top/kills"
  get "top/income"
  get "top/bounty"
  get "top/incursion"
  get "top/corp"
  get "top/alliance"
  get "top/mission"
  get "top/mission_time"
  get "top/mission_all"  
  get "ratopedia/factions"
  get "ratopedia/groups"
  get "search/ajax"
  get "search/ajax_rats"
  get "search/result"
  get "rats/faction/:faction", to: "rats#groups"
  get "rats/factions", to: "rats#factions"
  get "rats/type/:rat_type", to: "rats#rat_type"
  resources :rats
  get "wallet/index"
  get "home/test"
  get "home/legal"
  resources :chars

  resources :examples

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :keys
  resources :users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @wallet = WalletRecord.non_anon
    @kills = Kill.non_anon
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_log.html.haml
.well
  %h4 Recent Ticks
  .row
    .col-lg-12
  %p
  %table.table.vertical-middle.table-striped
    %tr
      %th.col-lg-2
        Timestamp
      %th
        Character
      %th
        Details
      %th.numeric
        Amount
    - @wallet.recent.each do |record|
      %tr
        %td= record.ts.strftime("%Y-%m-%d %H:%M:%S")
        %td
          = link_to eve_image(:char, record.char_id), char_path(record.char_id), class: :ttp, title: record.char_name
          = link_to eve_image(:corp, record.corp_id), corp_path(record.corp_id), class: :ttp, title: Corp.find(record.corp_id).name
          - if record.alliance_id
            = eve_image(:alliance, record.alliance_id)
        %td
          - if record.ref_type_id == 99
            = image_tag "http://image.eveonline.com/Alliance/500019_32.png", style: "display: inline"
            %b Incursion Reward
          - if record.ref_type_id == 34
            = image_tag "http://image.eveonline.com/Corporation/1000125_32.png", style: "display: inline"
            %b Agent Mission Time Bonus Reward
          - if record.ref_type_id == 33
            = image_tag "http://image.eveonline.com/Corporation/1000125_32.png", style: "display: inline"
            %b Agent Mission Reward
          - record.kills.each do |kill|
            - ttp = "<b>#{kill.rat_name}</b><br><i>#{kill.rat_type}</i>".html_safe
            = link_to eve_image(:rat, kill.rat_id, 32, ttp), rat_path(kill.rat_id)
        %td.numeric= nice_number(record.amount / 100.0, "ISK")

  .row
    .col-lg-12

app/views/home/_progress.html.haml
.well
  .blockquote-reverse.small-font
    %p
      - colonies = "<b class='yellow'>NPC Strongholds destroyed</b><br><i>#{nice_number(Kill.where(rat_type: "Deadspace Overseer's Sentry").count)}</i>"
      - headcounts = "<b class='yellow'>Characters on this site</b><br><i>#{nice_number(Char.count)}</i>"
      - ships = "<b class='yellow'>NPC Ships destroyed</b><br><i>#{ nice_number Kill.sum(:rat_amount) }</i>"
      - people = "<b class='yellow'>Deadspace Overseers killed</b><br><i>#{ nice_number Kill.overseer.sum(:rat_amount) }</i>"
      - isk = ( nice_number WalletRecord.sum(:amount) /100 ) + " ISK"
      - money = "<b class='yellow'>Total money earned</b><br><i>#{isk}</i>"

      Progress... What is it?
      Out here progress is numbers.
      Milimiters... Kilometers...
      %span.hand.ttp{ title: headcounts}
        %b.white
          Headcounts...
      Death tolls...
      This is progress.
      %span.hand.ttp{ title: colonies }
        %b.white
          Colonies burned...
      %span.hand.ttp{ title: ships }
        %b.white
          Ships destroyed...
      %span.hand.ttp{ title: people }
        %b.white
          People killed...
      %span.hand.ttp{ title: money }
        %b.white
          Money earned...
      It all comes at a price...
      And if the price is right
      I'll set the universe on fire
    %footer
      %cite{ title: "EVE Online, Inferno Trailer, 2012" }
        %a{ href: "http://www.youtube.com/watch?v=kED11aGobUk", target: "_blank" } EVE Online, Inferno Trailer, 2012
        / EVE Online, Inferno Trailer, 2012

app/views/home/corps.html.haml
= cache(cache_key) do
  .row
    .span6#kill_box
      %h4 Top bounty this month
      - top_corp_bounty_this_month.each do |top|
        .span1#kill
          %b
            = isk_short top["sum"]
          = corp_image_link(top["_id"])
          %br
          %b
            = corp_name_link(top["_id"])
    .span6#kill_box
      %h4 Top tax this month
      - top_tax_this_month.each do |top|
        .span1#kill
          %b
            = isk_short top["sum"]
          = corp_image_link(top["_id"])
          %br
          %b
            = corp_name_link(top["_id"])
  %br
  .row
    .span6#kill_box
      %h4 Top bounty last 10 days
      - top_corp_bounty_10days.each do |top|
        .span1#kill
          %b
            = isk_short top["sum"]
          = corp_image_link(top["_id"])
          %br
          %b
            = corp_name_link(top["_id"])
    .span6#kill_box
      %h4 Top tax last 10 days
      - top_tax_10days.each do |top|
        .span1#kill
          %b
            = isk_short top["sum"]
          = corp_image_link(top["_id"])
          %br
          %b
            = corp_name_link(top["_id"])
  %br
  .row
    .span6#kill_box
      %h4 Top bounty all time
      - top_corp_bounty.each do |top|
        .span1#kill
          %b
            = isk_short top["sum"]
          = corp_image_link(top["_id"])
          %br
          %b
            = corp_name_link(top["_id"])
    .span6#kill_box
      %h4 Top tax all time
      - top_tax.each do |top|
        .span1#kill
          %b
            = isk_short top["sum"]
          = corp_image_link(top["_id"])
          %br
          %b
            = corp_name_link(top["_id"])

app/views/home/index.html.haml
= cache WalletRecord.count do
  = render 'progress'
  .well
    .row
      - title = link_to "Income", top_income_path
      - title += " - Last 10 Days".html_safe
      = top_table(title, @wallet.top_income.last_ten_days.limit(5), :char, :isk, 4)
    
      - title = link_to "Bounty", top_bounty_path
      - title += " - Last 10 Days".html_safe
      = top_table(title, @wallet.top_income.bounty.last_ten_days.limit(5), :char, :isk, 4)
    
      - title = link_to "Incursion", top_incursion_path
      - title += " - Last 10 Days".html_safe
      = top_table(title, @wallet.top_income.incursion.last_ten_days.limit(5), :char, :isk, 4)
    .row
      - title = link_to "Mission Total", top_mission_all_path
      - title += " - Last 10 Days".html_safe
      = top_table(title, @wallet.top_income.mission_all.last_ten_days.limit(5), :char, :isk, 4)
    
      - title = link_to "Mission Rewards", top_mission_path
      - title += " - Last 10 Days".html_safe
      = top_table(title, @wallet.top_income.mission.last_ten_days.limit(5), :char, :isk, 4)
    
      - title = link_to "Mission Time Rewards", top_mission_time_path
      - title += " - Last 10 Days".html_safe
      = top_table(title, @wallet.top_income.mission_time.last_ten_days.limit(5), :char, :isk, 4)

    .row
      - title = link_to "Ticks", top_ticks_path
      - title += " - Last 10 Days".html_safe
      = top_table(title, @wallet.top_ticks.last_ten_days.limit(5), :char, :isk, 4)

      - title = link_to "Overseer Kills", top_kills_path
      - title += " - Last 10 Days".html_safe
      = top_table(title, @kills.overseer.top_kills.last_ten_days.limit(5), :char, :kill, 4)

      - title = link_to "Overseer Deaths", top_rats_path
      - title += " - Last 10 Days".html_safe
      = top_table(title, @kills.overseer.top_rats.last_ten_days.limit(5), :type, :kill, 4)
  = render 'log'

app/views/home/legal.html.haml
.well
  %h4 COPYRIGHT NOTICE
  %p 
    %a{href: "https://www.eveonline.com", target: :blank}
      EVE Online 
    and the EVE logo are the registered trademarks of CCP hf. All rights are reserved worldwide. All other trademarks are the property of their respective owners. 
    %a{href: "https://www.eveonline.com", target: :blank} 
      EVE Online
    , the EVE logo, EVE and all associated logos and designs are the intellectual property of CCP hf. All artwork, screenshots, characters, vehicles, storylines, world facts or other recognizable features of the intellectual property relating to these trademarks are likewise the intellectual property of CCP hf. CCP hf. has granted permission to 
    %a{ href: root_path} EVE Score 
    to use EVE Online and all associated logos and designs for promotional and information purposes on its website but does not endorse, and is not in any way affiliated with, 
    %a{ href: root_path} EVE Score. 
    CCP is in no way responsible for the content on or functioning of this website, nor can it be liable for any damage arising from the use of this website.

app/views/home/players.html.haml
= cache(cache_key) do
  .row
    .span6#kill_box
      %h4 Top bounty this month
      - top_bounty_this_month.each do |top|
        .span1#kill
          %b
            = isk_short top["sum"]
          = character_image_link(top["_id"])
          %br
          %b
            = character_name_link(top["_id"])
    .span6#kill_box
      %h4 Top bounty last 10 days
      - top_bounty_10days.each do |top|
        .span1#kill
          %b
            = isk_short top["sum"]
          = character_image_link(top["_id"])
          %br
          %b
            = character_name_link(top["_id"])
  %br
  .row
    .span6#kill_box
      %h4 Top Incursion rewards this month
      - top_incursion_this_month.each do |top|
        .span1#kill
          %b
            = isk_short top["sum"]
          = character_image_link(top["_id"])
          %br
          %b
            = character_name_link(top["_id"])
    .span6#kill_box
      %h4 Top bounty all time
      - top_bounty.each do |top|
        .span1#kill
          %b
            = isk_short top["sum"]
          = character_image_link(top["_id"])
          %br
          %b
            = character_name_link(top["_id"])
  %br
  .row
    .span6#kill_box
      %h4 Top kills last 10 days
      - top_kills_10days.each do |top|
        .span1#kill
          %b
            = top["kills"]
          = character_image_link(top["_id"])
          %br
          %b
            = character_name_link(top["_id"])
    .span6#kill_box
      %h4 Top kills all time
      - top_kills.each do |top|
        .span1#kill
          %b
            = top["kills"]
          = character_image_link top["_id"]
          %br
          %b
            = character_name_link top["_id"]
  %br
  .row
    .span6#kill_box
      %h4 Highest ticks last 10 days
      - highest_tick_10days.each do |top|
        .span1#kill
          %b
            = isk_short top[:bounty]
          = character_tick_link(top[:char_id],top[:_id])
          %br
          %b
            = character_name_link(top[:char_id])
    .span6#kill_box
      %h4 Highest ticks all time
      - highest_tick.each do |top|
        .span1#kill
          %b
            = isk_short top[:bounty]
          = character_tick_link(top[:char_id],top[:_id])
          %br
          %b
            = character_name_link(top[:char_id])

app/views/home/test.html.haml
.well
  %span{ "data-target" => "#yo", "data-toggle" => "collapse"} Click
  .row
    .col-lg-2
      dupa
    .col-lg-3
      dupa2
  .row
    .col-lg-2
      dupa
    .col-lg-3
      dupa2
  .row
    .col-lg-2
      dupa
    .col-lg-3
      dupa2
  .row.collapse.in#yo
    .col-lg-2
      COLLAPSE
    .col-lg-3
      COLLAPSE
  .row
    .col-lg-2
      dupa
    .col-lg-3
      dupa2