config/routes.rb
Evescore::Application.routes.draw do
  resources :sigs

  get "trust/grant"
  resources :scans do
    resources :sigs
  end
  
  get "scan/:secure_id", to: "scans#show"
  get "scan/:secure_id/edit", to: "scans#edit"
  get "tools/dps"
  get "stats/factions"
  get "stats/progress"
  resources :corps

  get "top/rats"
  get "top/ticks"
  get "top/kills"
  get "top/income"
  get "top/bounty"
  get "top/incursion"
  get "top/corp"
  get "top/alliance"
  get "top/mission"
  get "top/mission_time"
  get "top/mission_all"  
  get "ratopedia/factions"
  get "ratopedia/groups"
  get "search/ajax"
  get "search/ajax_rats"
  get "search/result"
  get "rats/faction/:faction", to: "rats#groups"
  get "rats/factions", to: "rats#factions"
  get "rats/type/:rat_type", to: "rats#rat_type"
  resources :rats
  get "wallet/index"
  get "home/test"
  get "home/legal"
  resources :chars

  resources :examples

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :keys
  resources :users
end

app/models/sig.rb
class Sig < ActiveRecord::Base
  belongs_to :scan
  belongs_to :char
  belongs_to :corp
  belongs_to :solar_system, foreign_key: :system_id
  belongs_to :cons
  belongs_to :region
  belongs_to :alliance
  belongs_to :sig_type
  belongs_to :sig_group
end

app/models/sig_type.rb
class SigType < ActiveRecord::Base
end

app/controllers/sigs_controller.rb
class SigsController < ApplicationController
  before_action :set_sig, only: [:show, :edit, :update, :destroy]
  before_filter :check_owner

  # GET /sigs
  def index
    @sigs = Sig.all
  end

  # GET /sigs/1
  def show
  end

  # GET /sigs/new
  def new
    @sig = Sig.new
  end

  # GET /sigs/1/edit
  def edit
  end

  # POST /sigs
  def create
    @sig = Sig.new(sig_params)

    if @sig.save
      redirect_to @sig, notice: 'Sig was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /sigs/1
  def update
    if @sig.update(sig_params)
      redirect_to @sig, notice: 'Sig was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /sigs/1
  def destroy
    @sig.destroy
    # redirect_to sigs_url, notice: 'Sig was successfully destroyed.'
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sig
      @sig = Sig.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sig_params
      params[:sig]
    end
    def check_owner
      if request.headers["HTTP_EVE_CHARID"].to_i == @sig.scan.char_id or ( user_signed_in? and  current_users.chars.ids.include? @sig.scan.char_id )
        true
      else
        flash[:error] = "Permission Denied"
        redirect_to :back
      end
    end
end

app/helpers/sigs_helper.rb
module SigsHelper
end

app/views/sigs/_form.html.haml
= form_for @sig do |f|
  - if @sig.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sig.errors.count, "error")} prohibited this sig from being saved:"
      %ul
        - @sig.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/sigs/edit.html.haml
%h1 Editing sig

= render 'form'

= link_to 'Show', @sig
\|
= link_to 'Back', sigs_path

app/views/sigs/index.html.haml
%h1 Listing sigs

%table
  %tr
    %th
    %th
    %th

  - @sigs.each do |sig|
    %tr
      %td= link_to 'Show', sig
      %td= link_to 'Edit', edit_sig_path(sig)
      %td= link_to 'Destroy', sig, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sig', new_sig_path

app/views/sigs/new.html.haml
%h1 New sig

= render 'form'

= link_to 'Back', sigs_path

app/views/sigs/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_sig_path(@sig)
\|
= link_to 'Back', sigs_path