config/routes.rb
Evescore::Application.routes.draw do
  resources :sigs

  get "trust/grant"
  resources :scans do
    resources :sigs
  end
  
  get "scan/:secure_id", to: "scans#show"
  get "scan/:secure_id/edit", to: "scans#edit"
  get "tools/dps"
  get "stats/factions"
  get "stats/progress"
  resources :corps

  get "top/rats"
  get "top/ticks"
  get "top/kills"
  get "top/income"
  get "top/bounty"
  get "top/incursion"
  get "top/corp"
  get "top/alliance"
  get "top/mission"
  get "top/mission_time"
  get "top/mission_all"  
  get "ratopedia/factions"
  get "ratopedia/groups"
  get "search/ajax"
  get "search/ajax_rats"
  get "search/result"
  get "rats/faction/:faction", to: "rats#groups"
  get "rats/factions", to: "rats#factions"
  get "rats/type/:rat_type", to: "rats#rat_type"
  resources :rats
  get "wallet/index"
  get "home/test"
  get "home/legal"
  resources :chars

  resources :examples

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :keys
  resources :users
end

app/models/char.rb
class Char < ActiveRecord::Base
  belongs_to :corp
  belongs_to :user
  belongs_to :key
  has_many :wallet_records
  has_many :kills
  
  def losses
    url = "https://zkillboard.com/api/losses/no-items/no-attackers/characterID/#{self.id}/"
  end
  
  def check
    key = self.key
    if ! key
      self.working = false
      self.save
      return false
    end
    api = key.api
    api.character_id = self.id
    chars = api.characters
    begin
      char = ( chars["eveapi"]["result"]["rowset"]["row"].select { |char| char["name"] == self.name } ).first
      char = char.rubify
      self.corp_id = char[:corporation_id]
      self.corp_name = char[:corporation_name]
      if char["alliance_id"].blank? == false
        self.alliance_id = char[:alliance_id]
        self.alliance_name = char[:alliance_name]
      end
      self.working = true
      self.save
    rescue 
      self.working = false
      self.save
      return false 
    end
  end
  
  def self.import(data)
    data=data.inject({}){|row,(k,v)| row[k.to_sym] = v; row}
    
    if data[:char_id] and data[:name] and data[:corp_id] and data[:corp_name]
      # check if corp is allied
      allied = Allied.where(corp_id: data[:corp_id]).first      
      if allied
        alliance_id = allied.alliance_id
        alliance_name = Alliance.find(alliance_id).name
      else
        alliance_name = nil
        alliance_id = nil
      end
      
      # check if corp exists
      corp = Corp.where(id: data[:corp_id]).first
      if ! corp
        corp = Corp.create(id: data[:corp_id], name: data[:corp_name], alliance_id: alliance_id, alliance_name: alliance_name)
      end
      
      # check if char exists
      char = Char.where(id: data[:char_id]).first
      
      if char
        char.update_attributes(id: data[:char_id], name: data[:name], corp_name: data[:corp_name], corp_id: data[:corp_id], alliance_name: alliance_name, alliance_id: alliance_id)
      else
        Char.create(id: data[:char_id], name: data[:name], corp_name: data[:corp_name], corp_id: data[:corp_id], alliance_name: alliance_name, alliance_id: alliance_id)
      end
    end
  end
  
  def wallet_import(rows=50)
    api = self.key
    if api 
      api = api.api
      api.row_count = rows
      api.character_id = self.id
      begin
        api_journal = api.wallet_journal["eveapi"]["result"]["rowset"]["row"]
        if api_journal and api_journal.class == Array
          api_journal.wallet_import
        end
      rescue
        nil
      end
    else
      nil
    end
  end
  def bounty
    self.wallet_records.bounty
  end
  def income
    self.wallet_records.sum(:amount)
  end
  
  def top_tick(t=nil)
    case t
    when :this_month
      tick = wallet_records.this_month.order("amount desc").first
      (tick.amount or 0) if tick
    when :last_ten_days 
      tick = wallet_records.last_ten_days.order("amount desc").first
      (tick.amount or 0) if tick
    else
      tick = wallet_records.order("amount desc").first
      (tick.amount or 0) if tick
    end
  end    
  def bounty_rank
    ranks = {}
    i=0
    WalletRecord.top_bounty.each do |char|
      i+=1
      tmp = { char.id => i }
      ranks.merge! tmp
    end
    ranks[self.id]
  end
end

app/controllers/chars_controller.rb
class CharsController < ApplicationController
  before_action :set_char, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [ :show ]
  before_filter :check_users_chars, only: [ :index ]
  before_filter :check_anon, only: [ :show ]

  # GET /chars
  # GET /chars.json
  def index
    @chars = Char.where("user_id = #{current_user.id} and ( anon = 1 or anon <> 1 or anon is null )")
  end

  # GET /chars/1
  # GET /chars/1.json
  def show
    @wallet = @char.wallet_records.order("ts desc").page(params[:page]).per(5)
  end

  # GET /chars/new
  def new
    @char = Char.new
  end

  # GET /chars/1/edit
  def edit
  end

  # POST /chars
  # POST /chars.json
  def create
    @char = Char.new(char_params) 

    respond_to do |format|
      if @char.save
        format.html { redirect_to @char, notice: 'Char was successfully created.' }
        format.json { render action: 'show', status: :created, location: @char }
      else
        format.html { render action: 'new' }
        format.json { render json: @char.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chars/1
  # PATCH/PUT /chars/1.json
  def update
    respond_to do |format|
      if @char.update(char_params)
        format.html { redirect_to chars_url, notice: 'Char was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @char.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chars/1
  # DELETE /chars/1.json
  def destroy
    @char.destroy
    respond_to do |format|
      format.html { redirect_to chars_url }
      format.json { head :no_content }
    end
  end

  private
  
    def check_anon
      if @char.anon == true
        redirect_to root_path unless ( user_signed_in? and @char.user_id == current_user.id )
      end
    end
  
    def check_users_chars
      if user_signed_in?
        if current_user.chars.where("user_id = #{current_user.id} and ( anon = 1 or anon <> 1 or anon is null )").count == 0
          flash[:warning] = "User doesn't have any characters. Add an API Key"
          redirect_to new_key_path
        end
      end
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_char
      @char = Char.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def char_params
      params[:char].permit(:anon)
    end
end

app/helpers/chars_helper.rb
module CharsHelper
end

app/views/chars/_form.html.haml
= form_for @char do |f|
  - if @char.errors.any?
    #error_explanation
      %h2= "#{pluralize(@char.errors.count, "error")} prohibited this char from being saved:"
      %ul
        - @char.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/chars/_help.html.haml
#hidden-help.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
        %h4.modal-title What does hidden mean?
      .modal-body
        %p
          This field specifies if the character is visible to public.
        %p
          By defaut it is set to 
          %i false 
          (unchecked), which means a character is visible.
          After checking this box, the character will become visible only to your user, after being logged in.
        
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/chars/_log.html.haml
.well
  %p
    %h4 
      Recent Activity
      
  %br
  %table.table.vertical-middle.table-striped
    %tr
      %th.col-lg-2
        Timestamp
      %th
        Character
      %th
        Details
      %th.numeric
        Amount
    - @wallet.each do |record|
      %tr
        %td= record.ts.strftime("%Y-%m-%d %H:%M:%S")
        %td
          = eve_image(:char, record.char_id)
          = eve_image(:corp, record.corp_id)
          - if record.alliance_id
            = eve_image(:alliance, record.alliance_id)
        %td
          - if record.ref_type_id == 99
            = image_tag "http://image.eveonline.com/Alliance/500019_32.png", style: "display: inline"
            %b Incursion Reward
          - if record.ref_type_id == 34
            = image_tag "http://image.eveonline.com/Corporation/1000125_32.png", style: "display: inline"
            %b Agent Mission Time Bonus Reward
          - if record.ref_type_id == 33
            = image_tag "http://image.eveonline.com/Corporation/1000125_32.png", style: "display: inline"
            %b Agent Mission Reward
          - record.kills.each do |kill|
            - ttp = "<b>#{kill.rat_name}</b><br><i>#{kill.rat_type}</i>".html_safe
            = link_to eve_image(:rat, kill.rat_id, 32, ttp), rat_path(kill.rat_id)
        %td.numeric
          = number_to_isk record.amount

app/views/chars/edit.html.haml
%h1 Editing char

= render 'form'

= link_to 'Show', @char
\|
= link_to 'Back', chars_path

app/views/chars/index.html.haml
.well
  %h3 Listing chars
  %hr
    %table.table.table-striped.vertical-middle
      %tr
        %th.small-img-col
        %th Name
        %th.right
          Hidden
          %i.glyphicon.glyphicon-question-sign.ttp{ title: "What does this field do? Click to find out!", "data-target" => "#hidden-help", "data-toggle" => "modal" }
        %th

      - @chars.each do |char|
        %tr
          %td
            = link_to eve_image(:char, char.id), char
          %td
            = link_to char.name, char
          = form_for char do |f|
            %td.right
              = f.check_box :anon
            %td.right
              = f.submit "Save", class: "btn btn-primary"
              &nbsp;
              = link_to 'Delete', char, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger"

= render :partial => 'help'

app/views/chars/new.html.haml
%h1 New char

= render 'form'

= link_to 'Back', chars_path

app/views/chars/show.html.haml
.row
  .col-lg-12
    .well
      .row
        .col-lg-3{ style: "width: 235px"}
          = eve_image(:char, @char.id, 64)
          = link_to eve_image(:corp, @char.corp_id, 64), corp_path(@char.corp_id)
          - if @char.alliance_id
            = eve_image(:alliance, @char.alliance_id, 64)
        .col-lg-9
          .row
            .col-lg-2
              %b
                Character
            .col-lg-10
              = @char.name
          .row
            .col-lg-2
              %b Corporation
            .col-lg-10
              = @char.corp_name
          - if @char.alliance_name
            .row
              .col-lg-2
                %b Alliance
              .col-lg-10
                = @char.alliance_name
.row
  .col-lg-12
    .well
      %table.table.table-striped
        %thead
          %tr
            %th.numeric
            %th.numeric
              Income
            %th.numeric
              Missions
            %th.numeric
              Bounty
            %th.numeric
              Incursions
            %th.numeric
              Best Ticks
        %tbody
          %tr
            %th
              Total
            %td.numeric= number_to_isk @char.wallet_records.sum(:amount)
            %td.numeric= number_to_isk @char.wallet_records.mission_all.sum(:amount)
            %td.numeric= number_to_isk @char.wallet_records.bounty.sum(:amount)
            %td.numeric= number_to_isk @char.wallet_records.incursion.sum(:amount)
            %td.numeric= number_to_isk @char.top_tick
          %tr
            %th
              This Month
            %td.numeric= number_to_isk @char.wallet_records.this_month.sum(:amount)
            %td.numeric= number_to_isk @char.wallet_records.mission_all.this_month.sum(:amount)
            %td.numeric= number_to_isk @char.wallet_records.bounty.this_month.sum(:amount)
            %td.numeric= number_to_isk @char.wallet_records.incursion.this_month.sum(:amount)
            %td.numeric= number_to_isk @char.top_tick(:this_month)

          %tr
            %th
              Last 10 Days
            %td.numeric= number_to_isk @char.wallet_records.last_ten_days.sum(:amount)
            %td.numeric= number_to_isk @char.wallet_records.last_ten_days.mission_all.sum(:amount)
            %td.numeric= number_to_isk @char.wallet_records.last_ten_days.bounty.sum(:amount)
            %td.numeric= number_to_isk @char.wallet_records.incursion.last_ten_days.sum(:amount)
            %td.numeric= number_to_isk @char.top_tick(:last_ten_days)
            
            
    

= render 'log'
= render :partial => 'layouts/disqus'